### ISSUE TITLE
Includes in views

### ISSUE THREAD

**Issue by urabenstein** [UniFormal/MMT#184] opened 2016-11-07 15:36 UTC
While trying to run Tom's physics units code, I've got an "no assignment found error". 
The setup is the following: There is a main theory A, B includes A, B' includes A, C includes B, D includes C. Now I would like to write a view from B' to D, which maps the new concepts of B' (the ones which are not included from A) to the ones in D and leaves everything else unchanged (so everything included from A should not be map anywhere, since D is using A as well and thus has the same concepts). This results in the following error: "error with unknown location: parse error: unknown error: class info.kwarc.mmt.api.GetError: get error: no assignment found: http://mathhub.info/MMT/physics-units?QEBase?QE". QEBase is the main theory (equivalent to A above).

**Comment by Jazzpirate** [comment] 2016-11-07 15:46
i.e. the problem is with mapping includes in views, in particular if the codomain doesn't directly include the same theory (only after flattening. I *think* if it directly includes the same theory, the structure checker doesn't complain)

**Comment by florian-rabe** [comment] 2016-11-07 15:49
That part was never fully implemented and verified.
It needs a full revision to hunt down all details.

**Comment by kohlhase** [comment] 2017-12-05 12:32
is this fixed by the parametric theories?

**Comment by Jazzpirate** [comment] 2017-12-05 12:40
No, by a different commit, but should be fixed by now :)

**Comment by florian-rabe** [comment] 2018-02-27 00:05
The interplay of includes and views is implemented up to minor bugs now.

**Closed by florian-rabe** 2018-02-27 00:05 UTC
Labels: Done -> Florian2Verify
