### ISSUE TITLE
MathScheme rename combinator: AdditiveUnaryAntiDistribution

### ISSUE THREAD

**Issue by yasminemmagdi** [UniFormal/MMT#245] opened 2017-12-04 18:50 UTC
The theory AdditiveUnaryAntiDistribution is defined as "UnaryAntiDistribution RENAME { + := * }". The expanded theory is: 
```
theory AdditiveUnaryAntiDistribution 
  include UnaryOperation 
  include Carrier 
  include Empty  
  include Magma 
  constant ax_antidis_prime_* : forall (x : U) formal (y : U) . prime (x * y) = (prime y) * (prime x) 
```
which uses * and does not rename to + 
![additiveunaryantidistribution](https://user-images.githubusercontent.com/22238052/33570185-018df172-d8fa-11e7-9a8d-d745b3dfde2e.png)

The file that has the library definitions can be found here: https://gl.mathhub.info/MMT/mathscheme/blob/master/source/MathScheme.mmt

**Comment by tkw1536** [comment] 2017-12-04 18:50
This should be an issue at https://gl.mathhub.info/MMT/mathscheme/issues instead.

**Comment by Jazzpirate** [comment] 2017-12-04 18:54
@tkw1536 we agreed on this at today's tetrapod meeting. It belongs here since it's an issue with our implementation of mathscheme-like theory expressions in MMT, not the content over at mathhub.

**Comment by Jazzpirate** [comment] 2017-12-04 19:03
@yasminemmagdi ah, this *might* actually the correct expansion after all:
Note that the pretty-printed type of ax_antidis_prime_* uses the *notations* of constants. Since * is used infix, I assume that in *some* theory, the constant * is declared and given a notation "1 * 2" (otherwise infix notation wouldn't be printed). With {+ = *} you are renaming some constant named "+" (which doesn't even seem to occur anywhere) with a new name "*", so:
1. If this theory should use + instead of *, then would't you want to use the renaming {* = +}?
2. For this to work, Unary_AntiDistribution would need a constant named "*" that you're renaming to "+"
3. The problem is, that what you apparently *actually* want is to change the *notation* rather than the name... I need to check whether that's possible and how...

or am I misinterpreting something?

**Comment by yasminemmagdi** [comment] 2017-12-04 19:14
@Jazzpirate:  
1. As far as I know from the code and previous discussions that renames works as (new_name := old_name). I think @florian-rabe can let us know which way is correct. 
2. * is defined in Magma and the ax_antidis_prime_* is  defined in the same format in the theory UnaryAntiDistribution, which is being renamed in this theory 
3. The flattened theories of MathScheme changes both, the name and the notation. But the notation is more important.

**Comment by Jazzpirate** [comment] 2017-12-04 21:00
@yasminemmagdi 
1. Ah yes, you're right, I was thinking of an earlier implementation and forgot that we changed that.
I'll look into it, I think I understand a lot better now how you want this to work :)

**Comment by yasminemmagdi** [comment] 2017-12-04 21:01
@Jazzpirate Great, Thank you

**Comment by yasminemmagdi** [comment] 2017-12-04 21:04
@Jazzpirate I know that Florian has made some updates that he has not passed to me yet. I thought of telling you so you do not end up working on an old version.

**Comment by Jazzpirate** [comment] 2017-12-04 21:23
Yes, I've talked to him already, thank you :)

**Comment by florian-rabe** [comment] 2018-02-27 01:11
I'm closing this because it is superseded by the latest devel (which Yasmine is already using).

**Closed by florian-rabe** 2018-02-27 01:11 UTC
