### ISSUE TITLE
Create stable branches inside MMT

### ISSUE THREAD

**Issue by tkw1536** [UniFormal/MMT#185] opened 2017-01-12 18:53 UTC
As decided with @kohlhase, we urgently need a solution to have some form of stability inside MMT. It can not be that demos constantly break and parts of the code committed are un-compilable. We already have [TRAVIS tests](https://travis-ci.org/UniFormal/MMT) that test if the code compiles, but these seem to be ignored most of the time. 

In order to resolve this problem we want to create a branching system inside MMT. We will have two main branches and switch to a [fork and pull based model of collaboration](https://help.github.com/articles/about-collaborative-development-models/). The two main branches are: 

* master -- This branch should contain a compilable version of MMT -- this can be checked automatically. For this we will enforce that the Travis Tests pass and only allow pull requests (and no direct pushes). 
* stable -- Similar to master this should contain a compilable version of MMT. On top of it being compilable we require this branch to be manually checked for stability, that is someone says "yes, this is a good version of MMT that actually works as intended". This also requires the Travis Tests as well as [Reviews](https://help.github.com/articles/about-pull-request-reviews/). 

To achieve this we need to do the following: 

* [x] Cleanup the [Travis Build File](https://github.com/UniFormal/MMT/blob/master/.travis.yml)
* [ ] Change the Travis Settings to compile pull requests
* [ ] Create master and stable branches
* [ ] [Protect](https://help.github.com/articles/about-branch-restrictions/)  the master and stable branches to only allow committing after tests pass
* [x] Write documentation for the new collaboration and testing process and in particular add  [Contribution Guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) for the repository

I will update this issue once the corresponding steps have been performed. 

/cc @kohlhase @florian-rabe  @Jazzpirate

**Comment by tkw1536** [comment] 2017-01-12 20:59
@kohlhase  I have written some documentation, can you tell me if [this](https://github.com/tkw1536/MMT/blob/stability/CONTRIBUTING.md) is good enough?

**Comment by florian-rabe** [comment] 2017-01-12 21:29
I support efforts to have a 'stable' branch in addition to 'master'.
There should be no push-restrictions on 'master' though (at least not for me).

The main challenge of the stable branch is the manpower needed to decide when (and which changes) to merge from master into stable.
Unfortunately, very little of that work can be automated with travis-like testing.

I suggest to invest into 2 things:
  - a description of the functionality that must work to allow merging
  - a person (student?) who periodically tests the functionality and merges from master to stable if it works.

I strongly oppose collaboration based on forks and pull-requests. (Note that MMT's license forbids distributing forked versions.)

Best,
Florian

**Comment by Jazzpirate** [comment] 2017-01-13 12:40
Ok, here's the problem, just with respect to the last couple of days:
- MMT suddenly didn't compile anymore, because something mmt-leo. Jonas can't properly work. Trying to fix mmt-leo yields some class "Matcher" which I didn't even know existed, and certainly not what needs to be changed how to make it compile again. Only meaningful solution was to just rename the project so I and Jonas can keep on working.
- I DEFINITELY want to keep a separate branch for when I do stupid things like timeouting typechecking of declarations in hacky ways, which should never be committed. But then again: git forces me to commit if I want to pull when there are merge conflicts blabla.
- Noticing, that the solver changed and the MMTStructureChecker changed, Rules changed, apparently there are priorities now. Reverting all my changes over the last weeks and repulling MMT results in nothing typechecking anymore, including LFX, which ODK and MitM depend on. Also, OML-parsing stopped working. Also, apparently the simplifier introduces variables which aren't declared in the context, throwing errors. Also, the solver throws away potentially applicable rules before they are tested for applicability. The last one I can fix, for the former I have no idea. 

The result is that LFX,ODK,MitM are currently unusable, working on PVS is pointless as long as I can't rely on the parser and typechecker and I need a working instance of MMT to finish up MitM at least far enough to be useful by MONDAY.

So... yeah. I applaud anything that makes it possible to a) have a reliably stable and not horribly outdated MMT branch that I can get back to in emergencies and b) pull without breaking everything because people (e.g. Florian - or admittedly myself :D ) push without properly testing.
</rant>

**Comment by kohlhase** [comment] 2017-01-13 12:54
I think that Dennis/Tom's proposal can easily made so that for you (Florian) nothing really changes: You make a fork of ```UniFormal/MMT``` in your personal git namespace (i.e. the repos ```florian-rabe/MMT```) and work on that. In particular, this (the master branch of this repos) is completely without commit restrictions, but a (separate) travis checks for compilability with each commit (for your information). Someone (Dennis has volunteered) regularly (e.g. when you deem the functionality ready and tell him) syncs your commits into the master branch of ```UniFormal/MMT```, which in the process always compiles. He would also push (similarly quality-checked) code from ```UniFormal/MMT``` to ```florian-rabe/MMT```, so that your fork stays in sync. 
With this, you can still work on ```florian-rabe/MMT``` via ```svn``` without restrictions. The only difference is in the URI, but ```UniFormal/MMT``` would at least compile (solving the SYNTAX problem).

**Comment by kohlhase** [comment] 2017-01-13 13:03
For the SEMANTICS problem I agree with your suggestion as well, let me elaborate a bit and put this into context. 

> I suggest to invest into 2 things: 
> 1. a description of the functionality that must work to allow merging 
> 2. a person (student?) who periodically tests the functionality and merges from master to stable if it works.

1. is something we need in any case. I remember from previous discussions that you probably think of regression tests (e.g. ```urtheories``` or ```exmples``` type-check). And I agree that this is very important. I would add the most important demos to the list here. 

Just as the ```master``` branch of ```UniFormal/MMT``` is the SYNTAX-checked branch of MMT, I suggest the ```stable``` branch of ```UniFormal/MMT``` to be the SEMANTICS-checked branch of MMT, that we base demos, archives, MathHub on, and that anyone who wants to do second-tier development syncs from. 

> a person (student?) who periodically tests the functionality and merges from master to stable if it works.

While I agree that I think that ultimately this is a human task (Tom has volunteered), we can partially automate the SEMANTICS-checking. At least type-checking ```urtheories``` is something travis can be made to do. If we have a semi-declarative representation of regression tests, we can even specify the revision of the archives to be tested clone the corresponding revision in travis (this is a concern that came up at lunch today). 

I think that this would go a long way towards SEMANTICS-checking; but we have to fix SYNTAX-checking as a base first.

**Comment by kohlhase** [comment] 2017-01-13 13:22
@Jazzpirate @tkw1536 
Just to be very clear, before you do anything to the repos config, we have to reach a consensus with Florian. 
Maybe it helps to have an MMT meeting about this in the near future?

**Comment by florian-rabe** [comment] 2017-01-13 19:37
Over the last couple of weeks I made lots of changes with some intermittent broken commits.
The reason was to finish Mizar with Mihnea.

I should have done that in a branch, but it's all stable now.

Regarding your concrete problems:

- MMT suddenly didn't compile anymore:

This is actually a trivial problem.
Some projects (e.g., mmt-leo) are outdated, and changes aren't always propagated to them.

In build.sbt, we should define two projects:
  - mmtAll that includes everything
  - mmt that includes only the stuff that is actually used.

- separate branch: You should have a separate branch indeed.
   It's important that your branch always works but still stays close to the trunk [*] - two mutually exclusive goals.
   I'm not quite sure how to handle that (or if git is good or bad at that).
   I suppose Michael and/or Tom can help you with that.

- This is the trickiest of the problems you mentioned. It's an instance of [*] specific to both of us working on the object checker.
   That code is extremely sensitive to changes and also difficult to test automatically.
   
   I see two things that we should do:
   - We should define a larger regression test suite - currently I'm using only MMT/examples.
   - We should see if we can refactor the object checker and related code so that all your changes are isolated in a class that only you work on.
     What exactly are you changing?

**Comment by florian-rabe** [comment] 2017-01-13 20:12
On 13.01.2017 14:03, Michael Kohlhase wrote:
> For the SEMANTICS problem I agree with your suggestion as well, let me elaborate a bit and put this into context.
>
>> I suggest to invest into 2 things:
>> 1. a description of the functionality that must work to allow merging
>> 2. a person (student?) who periodically tests the functionality and merges from master to stable if it works.
>
> 1. is something we need in any case. I remember from previous discussions that you probably think of regression tests (e.g. ```urtheories``` or ```exmples``` type-check). And I agree that this is very important. I would add the most important demos to the list here.

I was thinking of both automatable and non-automatable tests.

For example,
  - build.sbt deploy
  - mmt build MMT/urtheories, MMT/examples [*]
  - start web server, retrieve X, and see if it looks OK
What else should be on that list?

[*] caveat: There are occasionally minor problems, e.g., in the theorem prover examples, that I ignore because they're not high-priority enough to fix.

But automated, SYNTAX-focused tests can probably cover a lot already.

**Comment by florian-rabe** [comment] 2017-01-13 20:33
I've thought about setting up branches more but I'm still unsure what branches we need.

It's obvious that there should be a release branch that is always stable and that can be used by outsiders.

But we also need an internal release branch through which all insiders can get my changes quickly.
I don't know how to do that in a way that protects insiders from also getting the bugs I introduced.

**Comment by Jazzpirate** [comment] 2017-01-14 12:08
> What exactly are you changing?
Well, stupid stuff that shouldn't be committed. I modified the structure checker so that it stops checking a constant after e.g. 10min; I screwed around with judgement caching but obviously in a crude way, just to see how that might work and if it makes pvs checking faster without being completely wrong... stuff that shouldn't be committed, as I said :-D

My main problem was after reverting everything the realization that things that used to (and/or obviously should) typecheck suddenly don't anymore or even throw actual exceptions during typechecking.

> But we also need an internal release branch through which all insiders can get my changes quickly.
If I understand @tkw1536 correctly, that could just be your branch. I think everyone can pull from yours and merge it into theirs, it's just that yours (or anyones) branch won't be merged into master unless someone (e.g. me) does a pull request and it compiles - and only into release if someone (e.g. you) does a pull request knowing that this version is both syntactically *and* semantically working.

**Comment by kohlhase** [comment] 2017-01-15 05:47
> It's obvious that there should be a release branch that is always stable and that can be used by outsiders.

That is the branch I tentatively called ```stable``` on ```UniFormal/MMT```. I think that we also want to make "numbered releases" from time to time, if just for showing progress. But maybe we do not want to overdo things. The releases could just be tags on the ```stable``` branch.

**Comment by kohlhase** [comment] 2017-01-15 05:49
> But we also need an internal release branch through which all insiders can get my changes quickly.
> I don't know how to do that in a way that protects insiders from also getting the bugs I introduced.

that is the intention of the "protected" ```master``` branch on ```UniFormal/MMT```, where the "protection" is by a travis compile check (SYNTAX) a second pair of eyes (Dennis) for SEMANTICS.

**Closed** 2017-12-05 13:49 UTC
